# Workflow name
name: CI

# Define when to trigger the Workflow
on:
    push:
        branches:
            - master
jobs:
    print-greeting:
       runs-on: ubuntu-latest
    # Define steps to execute
       steps:
          - name: Check out code # This checkouts the github repository created.
            uses: actions/checkout@v2
          - name: Print greeting
            run: |
                    echo "Hello World!"
                    echo "This is the $current branch"